[package]
name = "add_vanilla_refs"
version = "0.0.1"
authors = ["Magicaldave <CorleyComputerRepair@protonmail.ch>"]
edition = "2021"

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "dev"